export {default as Home} from './home/Home'
export {default as Spaces} from './listSpaces/Spaces'
export {default as Contact} from './contact/Contact'
export {default as LogIn} from './login/LogIn'
export {default as Register} from './register/Register'
export {default as SpaceDetail} from './spaceDetail/SpaceDetail'
